### ISSUE TITLE
Option to parse ICU Messages at compile time

### ISSUE THREAD

**Issue by OliverJAsh** [seek-oss/vocab#73]
FormatJS/`react-intl` has an option to parse the ICU Message strings into an AST at compile time rather than at runtime. This improves performance at runtime (no need to parse on the fly) and reduces the size of the bundle by 40% (no need to bundle the ICU Message parser). https://formatjs.io/docs/guides/advanced-usage#react-intl-without-parser-40-smaller

Perhaps Vocab could have an option to do the same thing when we run `vocab compile`?

Alternatively, we could have an option to compile the ICU Message strings into functions, similar to this tool: https://github.com/cibernox/babel-plugin-precompile-intl (used by https://github.com/cibernox/svelte-intl-precompile).

**Comment by jahredhope** [comment]
If I understand correctly what your talking about is handled by `@vocab/webpack` the parsing will then be done at compile time and the resulting modules the user sees won't contain the ICU parser.
